package com.madeby.JAI

import java.util.Calendar

object DailyQuotes {

    val ALL = listOf(
        "\"The secret of getting ahead is getting started.\" \u2014 Mark Twain",
        "\"Success is the sum of small efforts, repeated day in and day out.\" \u2014 Robert Collier",
        "\"The future depends on what you do today.\" \u2014 Mahatma Gandhi",
        "\"It always seems impossible until it's done.\" \u2014 Nelson Mandela",
        "\"Education is the most powerful weapon which you can use to change the world.\" \u2014 Nelson Mandela",
        "\"The expert in anything was once a beginner.\" \u2014 Helen Hayes",
        "\"Well done is better than well said.\" \u2014 Benjamin Franklin",
        "\"Quality is not an act, it is a habit.\" \u2014 Aristotle",
        "\"Our greatest glory is not in never falling, but in rising every time we fall.\" \u2014 Confucius",
        "\"He who has a why to live can bear almost any how.\" \u2014 Friedrich Nietzsche",
        "\"Do what you can, with what you have, where you are.\" \u2014 Theodore Roosevelt",
        "\"The beautiful thing about learning is that no one can take it away from you.\" \u2014 B. B. King",
        "\"An investment in knowledge pays the best interest.\" \u2014 Benjamin Franklin",
        "\"The roots of education are bitter, but the fruit is sweet.\" \u2014 Aristotle",
        "\"Act as if what you do makes a difference. It does.\" \u2014 William James",
        "\"Do not wait to strike till the iron is hot, but make it hot by striking.\" \u2014 William Butler Yeats",
        "\"Perseverance is not a long race; it is many short races one after another.\" \u2014 Walter Elliot",
        "\"Knowing is not enough; we must apply. Willing is not enough; we must do.\" \u2014 Johann Wolfgang von Goethe",
        "\"The best way to predict the future is to create it.\" \u2014 Peter Drucker",
        "\"Don't watch the clock; do what it does. Keep going.\" \u2014 Sam Levenson",
        "\"Knowing yourself is the beginning of wisdom.\" \u2014 Aristotle",
        "\"We become what we repeatedly do.\" \u2014 Aristotle",
        "\"To improve is to change; to be perfect is to change often.\" \u2014 Winston Churchill",
        "\"The greatest victory is over yourself.\" \u2014 Plato",
        "\"No man ever steps in the same river twice.\" \u2014 Heraclitus",
        "\"Freedom is the power to choose our own chains.\" \u2014 Jean-Jacques Rousseau",
        "\"The unexamined life is not worth living.\" \u2014 Socrates",
        "\"The mind is not a vessel to be filled but a fire to be kindled.\" \u2014 Plutarch",
        "\"Patience is power.\" \u2014 Rumi",
        "\"Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.\" \u2014 Rumi",
        "\"Respond intelligently even to unintelligent treatment.\" \u2014 Lao Tzu",
        "\"Nature does not hurry, yet everything is accomplished.\" \u2014 Lao Tzu",
        "\"Be the change that you wish to see in the world.\" \u2014 Mahatma Gandhi",
        "\"Strength does not come from physical capacity. It comes from an indomitable will.\" \u2014 Mahatma Gandhi",
        "\"Live as if you were to die tomorrow. Learn as if you were to live forever.\" \u2014 Mahatma Gandhi",
        "\"Arise, awake, and stop not till the goal is reached.\" \u2014 Swami Vivekananda",
        "\"Take risks in your life. If you win, you can lead; if you lose, you can guide.\" \u2014 Swami Vivekananda",
        "\"All power is within you; you can do anything.\" \u2014 Swami Vivekananda",
        "\"Dream is not that which you see while sleeping; it is something that does not let you sleep.\" \u2014 A. P. J. Abdul Kalam",
        "\"Excellence happens not by accident. It is a process.\" \u2014 A. P. J. Abdul Kalam",
        "\"If you want to shine like a sun, first burn like a sun.\" \u2014 A. P. J. Abdul Kalam",
        "\"Failure will never overtake me if my determination to succeed is strong enough.\" \u2014 Og Mandino",
        "\"The best revenge is to be unlike him who performed the injury.\" \u2014 Marcus Aurelius",
        "\"Waste no time on what you cannot control.\" \u2014 Epictetus",
        "\"Difficulties are things that show what people are.\" \u2014 Epictetus",
        "\"The willing are led by fate; the unwilling are dragged.\" \u2014 Cleanthes",
        "\"To be everywhere is to be nowhere.\" \u2014 Seneca",
        "\"Every new beginning comes from some other beginning's end.\" \u2014 Seneca",
        "\"Without continual growth and progress, such words as improvement and success have no meaning.\" \u2014 Benjamin Franklin",
        "\"The journey itself is my home.\" \u2014 Matsuo Bash\u014D",
        "\"The only source of knowledge is experience.\" \u2014 Albert Einstein",
        "\"Logic will get you from A to B. Imagination will take you everywhere.\" \u2014 Albert Einstein",
        "\"Anyone who has never made a mistake has never tried anything new.\" \u2014 Albert Einstein",
        "\"Do not pray for an easy life; pray for the strength to endure a difficult one.\" \u2014 Bruce Lee",
        "\"Absorb what is useful, discard what is not.\" \u2014 Bruce Lee",
        "\"The successful warrior is the average man, with laser-like focus.\" \u2014 Bruce Lee",
        "\"The only true failure is the failure to learn.\" \u2014 John C. Maxwell",
        "\"Success is achieved and maintained by those who try and keep trying.\" \u2014 W. Clement Stone",
        "\"There is no substitute for hard work.\" \u2014 Thomas A. Edison",
        "\"The only limit to our realization of tomorrow is our doubts of today.\" \u2014 Franklin D. Roosevelt",
        "\"It does not matter how slowly you go as long as you do not stop.\" \u2014 Confucius",
        "\"Happiness depends upon ourselves.\" \u2014 Aristotle",
        "\"The mind is everything. What you think you become.\" \u2014 Gautama Buddha",
        "\"The best preparation for tomorrow is doing your best today.\" \u2014 H. Jackson Brown Jr.",
        "\"Energy and persistence conquer all things.\" \u2014 Benjamin Franklin",
        "\"Life is really simple, but we insist on making it complicated.\" \u2014 Confucius",
        "\"The greatest wealth is to live content with little.\" \u2014 Plato",
        "\"Do not let what you cannot do interfere with what you can do.\" \u2014 John Wooden",
        "\"If you can dream it, you can do it.\" \u2014 Walt Disney",
        "\"The way to get started is to quit talking and begin doing.\" \u2014 Walt Disney",
        "\"Success usually comes to those who are too busy to be looking for it.\" \u2014 Henry David Thoreau",
        "\"What lies behind us and what lies before us are tiny matters compared to what lies within us.\" \u2014 Ralph Waldo Emerson",
        "\"Fortune favors the bold.\" \u2014 Virgil",
        "\"The harder you work, the luckier you get.\" \u2014 Gary Player",
        "\"A journey is best measured in friends, rather than miles.\" \u2014 Tim Cahill",
        "\"What you do speaks so loudly that I cannot hear what you say.\" \u2014 Ralph Waldo Emerson",
        "\"Success is where preparation and opportunity meet.\" \u2014 Bobby Unser",
        "\"No act of kindness, no matter how small, is ever wasted.\" \u2014 Aesop",
        "\"The future belongs to those who prepare for it today.\" \u2014 Malcolm X",
        "\"The purpose of our lives is to be happy.\" \u2014 Dalai Lama",
        "\"Difficulties strengthen the mind, as labor does the body.\" \u2014 Seneca",
        "\"Waste no more time arguing what a good person should be. Be one.\" \u2014 Marcus Aurelius",
        "\"The soul becomes dyed with the color of its thoughts.\" \u2014 Marcus Aurelius",
        "\"He who learns but does not think is lost.\" \u2014 Confucius",
        "\"Knowledge speaks, but wisdom listens.\" \u2014 Jimi Hendrix",
        "\"The only impossible journey is the one you never begin.\" \u2014 Tony Robbins"
    )

    fun getTodayQuote(dayOfYear: Int = Calendar.getInstance().get(Calendar.DAY_OF_YEAR)): String {
        return ALL[dayOfYear % ALL.size]
    }
}
